### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by ansidev** [modelmapper/modelmapper#543] opened 2020-05-29 22:04 UTC
Link: http://modelmapper.org/user-manual/jooq-integration/

![Screenshot from 2020-05-30 05-02-53](https://user-images.githubusercontent.com/6688235/83309259-02aac800-a233-11ea-9741-e1767e1de223.png)

**Comment by chhsiao90** [comment] 2021-04-07 07:59
Thanks for reporting this issue, I will fix the documentation.

**Comment by chhsiao90** [comment] 2021-04-08 01:20
I checked the documentation, I can't find anything wrong. The example demonstrate how jooq extension work (see [RecordValueReaderTest](https://github.com/modelmapper/modelmapper/blob/master/extensions/jooq/src/test/java/org/modelmapper/jooq/RecordValueReaderTest.java)).

Can you point me out where the problem is? Thanks!

**Comment by ansidev** [comment] 2021-04-08 04:06
> I checked the documentation, I can't find anything wrong. The example demonstrate how jooq extension work (see [RecordValueReaderTest](https://github.com/modelmapper/modelmapper/blob/master/extensions/jooq/src/test/java/org/modelmapper/jooq/RecordValueReaderTest.java)).
> 
> Can you point me out where the problem is? Thanks!

@chhsiao90 You can see my screenshot. The problem is the second assertEquals: Customer object has not property `id`.

**Comment by chhsiao90** [comment] 2021-04-08 05:00
Thanks, fixed now.

**Closed by chhsiao90** 2021-04-08 05:00 UTC
Labels: Needs Info
