### ISSUE TITLE
ModelMapper and Java 9

### ISSUE THREAD

**Issue by akabynga** [modelmapper/modelmapper#296] opened 2018-01-02 16:10 UTC
It seems that ModelMapper does not work with Java 9. (The same code working with Java 8)

Exception in thread "main" org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Failed to configure mappings

1 error
	at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:213)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:89)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:103)
	at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:94)
	at com.epam.spring.App.main(App.java:13)
Caused by: java.lang.IllegalArgumentException
	at org.modelmapper.internal.asm.ClassReader.<init>(Unknown Source)
	at org.modelmapper.internal.asm.ClassReader.<init>(Unknown Source)
	at org.modelmapper.internal.asm.ClassReader.<init>(Unknown Source)
	at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:224)
	at org.modelmapper.PropertyMap.configure(PropertyMap.java:382)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:196)
	... 4 more

```
public class App {

	public static void main(String[] args) {
		System.out.println("Hello World!");

		UserTest usertest = new UserTest();
		usertest.setTest("TEST");

		ModelMapper mapper = new ModelMapper();
		mapper.addMappings(new UserTestMapping());
		System.out.println("Hello World!");

		UserTestDTO dto = mapper.map(usertest, UserTestDTO.class);
		System.out.println(dto);
	}
}
```

```
public class UserTest {

	private String test;

	public String getTest() {
		return test;
	}

	public void setTest(String test) {
		this.test = test;
	}
}
```

```
public class UserTestDTO {

	private String anotherTestString;

	public String getAnotherTestString() {
		return anotherTestString;
	}

	public void setAnotherTestString(String anotherTestString) {
		this.anotherTestString = anotherTestString;
	}

	@Override
	public String toString() {
		return new StringBuilder().append("string: " + anotherTestString).toString();
	}
}
```

```
public class UserTestMapping extends PropertyMap<UserTest, UserTestDTO> {

	@Override
	protected void configure() {
		map().setAnotherTestString(source.getTest());
	}
}
```

**Comment by jhalterman** [comment] 2018-01-02 17:51
Might need to upgrade ASM...

**Comment by piotr0000** [comment] 2018-02-28 00:40
Hello. I can't reproduce your problem. I use above source code compiled on Java 8 and run on Java 9 and it works correctly. Last line from main shows "string: TEST" without any exceptions. 
1. Which version of modelmapper do you use ? 
2. Do you use other libraries in project ? Maybe some dependencies conflict causes problem in your project.
3. Which version of Java do you use to compile your project ?

**Comment by glains** [comment] 2018-03-03 11:05
I can also confirm this error using Java version 9.0.4 and
```
<dependency>
    <groupId>org.modelmapper</groupId>
    <artifactId>modelmapper</artifactId>
    <version>1.1.2</version>
</dependency>
```

I used nearly the same test classes as described above:
```
public class Main {

    public static void main(String[] args) {
        UserTest usertest = new UserTest();
        usertest.setTest("TEST");

        ModelMapper mapper = new ModelMapper();
        mapper.addMappings(new PropertyMap<UserTestDTO, UserTest>() {
            @Override
            protected void configure() {
                map().setTest(source.getTest());
            }
        });
        mapper.map(usertest, UserTestDTO.class);
    }

    private static class UserTest {

        private String test;

        public String getTest() {
            return test;
        }

        public void setTest(String test) {
            this.test = test;
        }
    }

    private static class UserTestDTO {

        private String test;

        public String getTest() {
            return test;
        }

        public void setTest(String test) {
            this.test = test;
        }
    }
}
```

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.modelmapper.internal.cglib.core.ReflectUtils$1 (file:/C:/Users/lukas/.m2/repository/org/modelmapper/modelmapper/1.1.2/modelmapper-1.1.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Failed to configure mappings

1 error
	at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:213)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:89)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:112)
	at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:94)
	at de.kannenberg.Main.main(Main.java:16)
Caused by: java.lang.NullPointerException
	at org.modelmapper.internal.ExplicitMappingBuilder$ExplicitMappingInterceptor.access$000(ExplicitMappingBuilder.java:284)
	at org.modelmapper.internal.ExplicitMappingBuilder.createAccessorProxies(ExplicitMappingBuilder.java:267)
	at org.modelmapper.internal.ExplicitMappingBuilder.createProxies(ExplicitMappingBuilder.java:257)
	at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:236)
	at org.modelmapper.PropertyMap.configure(PropertyMap.java:382)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:196)
	... 4 more
```

**Comment by piotr0000** [comment] 2018-03-03 12:27
@glains, I checked that your code also doesn't work on Java 8 or later. It throws similar exception like yours. The reason is that you're using static classes. When you use non static classes (typical objects in fact), it works correctly on Java 8 & Java 9. By the way, last merged commit: "Updates asm, cglib and objenesis to their latest versions" https://github.com/modelmapper/modelmapper/commit/d66343ed9eb10d91220baa0a5a2a4be66e212ae3
where asm and other libraries was upgraded, causes that modelmapper from master branch should work correctly with Java 9.

**Comment by glains** [comment] 2018-03-03 13:16
Great stuff, i will check that in a moment and reply here. However, i originally found this issue since my project has the same problem, but i am using pojos there, not static classes.

**Comment by piotr0000** [comment] 2018-03-03 13:57
Please check all your issues using modelmapper from branch: master (not 1.1.2 version)

**Comment by chhsiao90** [comment] 2018-03-16 07:17
I will check if #300 fix some java 9 problem, and will cut a release this weekend.

**Comment by piotr0000** [comment] 2018-03-19 00:22
Great. Please close this post (#296).

**Comment by chhsiao90** [comment] 2018-03-21 05:27
I had a release v1.1.3 with the dependency update, please take a look if this fix the issue, thanks.

**Comment by piotr0000** [comment] 2018-03-21 23:25
Thanks. I confirm. Please close this post (#296).

**Closed** 2018-03-22 04:02 UTC
