### ISSUE TITLE
Using modelmapper 2.3.8 with java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by elmer25** [modelmapper/modelmapper#561] opened 2020-09-11 01:22 UTC
I am running with org.modelmapper:modelmapper:2.3.8 from Maven Central at https://search.maven.org/search?q=g:org.modelmapper

When I attempt to run the ModelMapper inside an assembler (see below), 

`public class AccountAssembler implements DtoEntityAssembler<AccountEntity, AccountDto> {

  private static final AddressAssembler addressAssembler = new AddressAssembler();
  
  private static final PhoneAssembler phoneAssembler = new PhoneAssembler();
  
  public AccountEntity toEntity(AccountDto account) {
    ModelMapper mapper = new ModelMapper();
    mapper.createTypeMap(AccountDto.class, AccountEntity.class)
      .addMapping(AccountDto::getAccountId, AccountEntity::setAccountId)  // Integer
      .addMapping(AccountDto::getAddress, AccountEntity::setAddress)        
      .addMapping(AccountDto::getBookerAccountKey, AccountEntity::setBookerAccountKey) // String
      .addMapping(AccountDto::getEmail, AccountEntity::setEmail) // String
      .addMapping(AccountDto::getKey, AccountEntity::setKey) // String
      .addMapping(AccountDto::getMap, AccountEntity::setMap) // String
      .addMapping(AccountDto::getName, AccountEntity::setName) // String
      .addMapping(AccountDto::getWebsite, AccountEntity::setWebsite); // String
    return mapper.map(account, AccountEntity.class);
  }

  public AccountDto toDto(AccountEntity account) {
    ModelMapper mapper = new ModelMapper();
    mapper.createTypeMap(AccountEntity.class, AccountDto.class)
      .addMapping(AccountEntity::getAccountId, AccountDto::setAccountId)
      .addMapping(AccountEntity::getAddress, (dest, v) -> dest.setAddress(addressAssembler.toDto((AddressEntity) v)))
      .addMapping(AccountEntity::getBookerAccountKey, AccountDto::setBookerAccountKey)
      .addMapping(AccountEntity::getEmail, AccountDto::setEmail)
      .addMapping(AccountEntity::getKey, AccountDto::setKey)
      .addMapping(AccountEntity::getMap, AccountDto::setMap)
      .addMapping(AccountEntity::getName, AccountDto::setName)
      .addMapping(AccountEntity::getWebsite, AccountDto::setWebsite);
    return mapper.map(account, AccountDto.class);
  }

}`

I get the following root cause in my stack trace:

`Caused by: java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory not found by modelmapper [18]`

I am using the Apache Felix framework. From my research, I understand that the sunb.reflect is not publicly available. I don't know how to work around this currently. Are there any ideas? 

I am currently running Java 8 and want to upgrade to the most recent Java version at a future time. I will remain running within a Java framework like Felix or similar.

Any ideas how to get around this would be greatly appreciated.

**Comment by mladBlum** [comment] 2020-09-15 12:00
I think this issue is related to this one: https://github.com/modelmapper/modelmapper/issues/426

**Comment by chhsiao90** [comment] 2021-04-06 05:36
Can you check if latest modelmapper can reproduce this issue? Thanks!

**Comment by mladBlum** [comment] 2021-04-06 07:55
I am not the thread owner. Nevertheless I cannot reproduce the issue in the latest release (2.4.0). I was able to completly remove the jdk.unsupported attribute.

Thank you!

**Comment by chhsiao90** [comment] 2021-04-06 07:58
Thanks for the feedback! I will close the issue. Please feel free to reopen this issue or create a new one if this issue was still reproducible.

**Closed by chhsiao90** 2021-04-06 07:58 UTC
Labels: Needs Info
