### ISSUE TITLE
JDBI with ModelMapper: ResultSet with null values

### ISSUE THREAD

**Issue by colt7** [modelmapper/modelmapper#168] opened 2015-11-24 09:22 UTC
Hi, i'm using ModelMapper with JDBI, and I have an error mapping the ResultSet into a MyObject: if the first row of ResultSet has a column with null value (table.column2 = null), modelmapper doesn't create a correct mapper. In fact for all the rows of the resultset, that value will be mapped as null, because modelMapper creates the mapper the first time, starting from the values contained in the first row.

Example 1:

table1 - col1, col2, col3

rs = "1", "customer", "50"
"2", "customer", "50"
"3", null, null

It works!

Example 2:

table1 - col1, col2, col3

rs = "3", null, null
"1", "customer", "50"
"2", "customer2", "50"

the column 2 and column 3 will be null for all the rows.

How to resolve this issue?
Regards, bye bye

**Comment by sergemat** [comment] 2016-11-25 06:23
I ran into the same issue few days ago. The PropertyInfoSetResolver.resolveAccessors() method skips creation of an accessor if some ValueReader is used and returned value is null. I guess that for simple value readers such as MapValueReader this could be the only option, but for more sophisticated readers that could provide information about the value type this approach is very limiting.

I suggest adding new method to ValueReader interface that can return member type if member value is null.

`Class<?> getType(T source, String memberName)`

The default implementation can return either null or Object.class.

In this case, it will be possible to implement ResultSetValueReader that reads values and type info from SQL ResultSet metadata and expose it as real JDBI integration / extension. 

I have this approach implemented in my local copy of ModelMapper and it works great. Please let me know if this is something that other people will be interested in and I will create pull request.

**Comment by carofe82** [comment] 2017-01-11 23:23
@sergemat It would be great if you share the pull request :). Thank you.

**Comment by carofe82** [comment] 2017-01-12 16:14
Test Case:
```java
package org.modelmapper.internal.valueaccess;

import java.util.HashMap;
import java.util.Map;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.NameTokenizers;
import org.testng.annotations.Test;
import static org.testng.Assert.*;

@Test(groups = "functional")
public class MapValueReaderTwoConsecutiveMapsTest {
	
	public static class Row {
		private String column1;
		private String column2;
		
		public String getColumn1() {
			return column1;
		}
		public void setColumn1(String column1) {
			this.column1 = column1;
		}
		public String getColumn2() {
			return column2;
		}
		public void setColumn2(String column2) {
			this.column2 = column2;
		}
		
	}

	@Test
	public void shouldMapMapWithNullsToBean() {
		ModelMapper modelMapper = new ModelMapper();
		
		Map<String, Object> row1 = new HashMap<String, Object>();
		row1.put("column1", null);
		row1.put("column2", "row1value2");
		
		Map<String, Object> row2 = new HashMap<String, Object>();
		row2.put("column1", "row2value1");
		row2.put("column2", "row2value2");
		
		Row rowObject1 = modelMapper.map(row1, Row.class);
		Row rowObject2 = modelMapper.map(row2, Row.class);
		
		assertEquals(rowObject1.getColumn1(), null);
		assertEquals(rowObject1.getColumn2(), "row1value2");
		assertEquals(rowObject2.getColumn1(), "row2value1");
		assertEquals(rowObject2.getColumn2(), "row2value2");

	}
}
```

**Comment by carofe82** [comment] 2017-01-12 16:40
@jhalterman This is an approach for the fix following @sergemat idea.

* Should `getMemberType` be called `getMemberInitialType`?
* The naming doesn't make it clear that `getMemberType` will be invoked if the type can't be inferred from the actual value. Javadoc can help but it will still be confusing. Should that method become the source of truth regarding type? then you would ask, why not from the value? Another approach would be to make `get` to return an object with the value and the type:
```java
public class ValueAndType {
	private final Object value;
	private final Class<?> type;
	public ValueAndType(Object value, Class<?> type) {
		this.value = value;
		this.type = type;
	}
	public ValueAndType(Object nonNullValue) {
		Validate.notNull(nonNullValue, "nonNullValue cannot be null");
		this.value = nonNullValue;
		this.type = nonNullValue.getClass();
	}
	...
}
```

Please let me know what you think and I can do a pull request. Thank you.

```java
diff --git a/core/src/main/java/org/modelmapper/internal/PropertyInfoSetResolver.java b/core/src/main/java/org/modelmapper/internal/PropertyInfoSetResolver.java
index 58490a4..e52ca35 100644
--- a/core/src/main/java/org/modelmapper/internal/PropertyInfoSetResolver.java
+++ b/core/src/main/java/org/modelmapper/internal/PropertyInfoSetResolver.java
@@ -81,6 +81,9 @@ final class PropertyInfoSetResolver<T> {
         if (sourceValue != null)
           accessors.put(nameTransformer.transform(memberName, NameableType.GENERIC),
               new ValueReaderPropertyInfo(valueReader, sourceValue, memberName));
+        else
+          accessors.put(nameTransformer.transform(memberName, NameableType.GENERIC),
+                    new ValueReaderPropertyInfo(valueReader, valueReader.getMemberType(source, memberName), memberName));
       }
     }
     return accessors;
diff --git a/core/src/main/java/org/modelmapper/internal/valueaccess/MapValueReader.java b/core/src/main/java/org/modelmapper/internal/valueaccess/MapValueReader.java
index caba931..c686ca6 100644
--- a/core/src/main/java/org/modelmapper/internal/valueaccess/MapValueReader.java
+++ b/core/src/main/java/org/modelmapper/internal/valueaccess/MapValueReader.java
@@ -35,4 +35,8 @@ public class MapValueReader implements ValueReader<Map<String, Object>> {
   public Collection<String> memberNames(Map<String, Object> source) {
     return source.keySet();
   }
+
+  public Class<?> getMemberType(Map<String, Object> source, String memberName) {
+    return Object.class;
+  }
 }
diff --git a/core/src/main/java/org/modelmapper/spi/ValueReader.java b/core/src/main/java/org/modelmapper/spi/ValueReader.java
index 4829215..644bd64 100644
--- a/core/src/main/java/org/modelmapper/spi/ValueReader.java
+++ b/core/src/main/java/org/modelmapper/spi/ValueReader.java
@@ -30,6 +30,14 @@ public interface ValueReader<T> {
    * @throws IllegalArgumentException if the {@code memberName} is invalid for the {@code source}
    */
   Object get(T source, String memberName);
+  
+  /**
+   * Returns the type of the {@code memberName} in {@code source}. This method will be used
+   * when the type cannot be inferred because the member value is null.
+   * @param memberName -
+   * @return the member type
+   */
+  Class<?> getMemberType(T source, String memberName);
```

**Comment by jhalterman** [comment] 2017-01-12 18:04
@carofe82 Could you give a quick description of this change/diff as you understand it? Then I can better weigh in on your questions.

As I recall, the general problem with mapping values is that ModelMapper builds a TypeMap based on the first record it sees, which may or may not look like subsequent records.

**Comment by carofe82** [comment] 2017-01-12 19:49
The problems I see:
The `PropertyInfoSetResolver.resolveAccessors` was not setting an accessor for the property if the value is null:
```java
if (sourceValue != null)
           accessors.put(nameTransformer.transform(memberName, NameableType.GENERIC),
               new ValueReaderPropertyInfo(valueReader, sourceValue, memberName));
```
And since this map of accessors is cached, it was being set once when you do the `map` for the first time. So the missing accessor seems to be the cause of the problem.
The solution in the diff is basically to provide the `ValueReader` with a method the code can fall back if the `sourceValue` is null. Then just it was a matter of adding an `else` to the original `if` to get the initial type from the `ValueReader`:

```java
        else
          accessors.put(nameTransformer.transform(memberName, NameableType.GENERIC),
                    new ValueReaderPropertyInfo(valueReader, valueReader.getMemberType(source, memberName), memberName));
```

Does that make sense?

**Comment by sergemat** [comment] 2017-01-12 21:17
I created pull request #195 with my changes. I was able to use these in my business app that uses DropWizard 0.9.2 and JDBI.  Please review much changes as much as possible because Java is not my primary language.

**Closed** 2017-05-09 07:02 UTC
