### ISSUE TITLE
LocalDateTime null when cloning

### ISSUE THREAD

**Issue by PagnieauJonathan** [modelmapper/modelmapper#596] opened 2021-03-26 15:42 UTC
Hello,

I encountered an issue when cloning an object with modelmapper. Basically, LocalDateTime are not cloned and is set to null on the new instance. On the other hand, this issue does not appear when mapping different class with LocalDateTime .

Here is a little example :
```

import static org.junit.Assert.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;
import org.modelmapper.ModelMapper;

class DemoEntity {
    
    private LocalDateTime date;
    private String name;
    
    public LocalDateTime getDate() {
        return date;
    }
    
    public void setDate(LocalDateTime date) {
        this.date = date;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public int hashCode() {
        return Objects.hash(date, name);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        DemoEntity other = (DemoEntity) obj;
        return Objects.equals(date, other.date) && Objects.equals(name, other.name);
    }
}

class DemoDTO {
    
    private LocalDateTime date;
    private String name;
    
    public LocalDateTime getDate() {
        return date;
    }
    
    public void setDate(LocalDateTime date) {
        this.date = date;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public int hashCode() {
        return Objects.hash(date, name);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        DemoDTO other = (DemoDTO) obj;
        return Objects.equals(date, other.date) && Objects.equals(name, other.name);
    }
}

public class TestDemoLocalDateTime {
    
    @Test
    void testMapEntityToDTO() {
        
        ModelMapper modelMapper = new ModelMapper();
        
        DemoEntity entity = new DemoEntity();
        entity.setName("demo");
        LocalDateTime date = LocalDateTime.now();
        entity.setDate(date);
        
        DemoDTO expected = new DemoDTO();
        expected.setName("demo");
        expected.setDate(date);
        
        DemoDTO actual = modelMapper.map(expected, DemoDTO.class);
        
        assertEquals(expected, actual);
    }
    
    @Test
    void testClone() {
        
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setDeepCopyEnabled(true);
        
        DemoDTO expected = new DemoDTO();
        expected.setName("demo");
        LocalDateTime date = LocalDateTime.now();
        expected.setDate(date);
        
        DemoDTO actual = modelMapper.map(expected, DemoDTO.class);
        
        assertNotNull(actual.getDate());
        assertEquals(expected, actual);
    }
}
```

The first test will pass and will work perfectly ("date" is cloned).

But the second test will fail with the first assertion, The "date" is null.

Is there any solution to resolve this ?

PS : I'm using ModelMapper 2.3.8 and Java 8

**Comment by chhsiao90** [comment] 2021-03-30 03:31
Have you tried the `Jsr310Module` from [modelmapper/modelmapper-module-java8](https://github.com/modelmapper/modelmapper-module-java8)?

**Comment by PagnieauJonathan** [comment] 2021-03-30 06:45
Thank you, it seems to work. I thought Jsr310Module was only to parse LocalDateTime to another type. It's still strange that when we are mapping differents classes, we don't need Jsr310Module but when cloning we have to use it.

**Comment by chhsiao90** [comment] 2021-03-30 06:57
You are right, the `Jsr310Module` was used for parsing LocalDateTime.

For `LocalDateTime -> LocalDateTime` mapping, it caused unexpected behavior when `setDeepCopyEnabled` enabled as modelmapper will check fields from LocalDateTime.

The simplest way to fix the issue is to create a TypeMap<LocalDateTime, LocalDateTime> by `modelMapper.typeMap(LocalDateTime.class, LocalDateTime.class)`, if the `setDeepCopyEnabled` must be enabled.

**Comment by chhsiao90** [comment] 2021-04-08 03:27
I guessed we can close this issue? Feel free to reopen this issue or create new one if you still have questions. Thanks.

**Closed by chhsiao90** 2021-04-08 03:27 UTC
Labels: Question
