### ISSUE TITLE
ModelMapper and Java 10

### ISSUE THREAD

**Issue by user140547** [modelmapper/modelmapper#322] opened 2018-04-12 07:02 UTC
Similarily to this issue #296 , Modelmapper does not work with Java 10. Although the class file format has not changed (and I don't know if any other changes are necessary), the version has been updated to 54, and there is a check that the version must not be >53

```
Caused by: java.lang.IllegalArgumentException
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:160)
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:143)
```

**Comment by chhsiao90** [comment] 2018-04-12 07:16
We need to update cglib to 3.2.6 and asm to 6.0 to support Java 10.

**Comment by chhsiao90** [comment] 2018-04-13 04:08
It should be fixed by #323 .

**Comment by oks5228** [comment] 2018-04-18 13:46
Explicit mapping using PropertyMap is not working with Java 10 (target and source compatibility).

I built library on my own using commit f2581ca. I'm including 
[zip file with project](https://github.com/modelmapper/modelmapper/files/1924232/mapovani.zip) to induce this behaviour.

`Exception in thread "main" org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Failed to configure mappings

1 error
	at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:213)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:89)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:112)
	at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:94)
	at oks.playground.mapovani.App.main(App.java:23)
Caused by: java.lang.IllegalArgumentException
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:160)
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:143)
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:418)
	at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:224)
	at org.modelmapper.PropertyMap.configure(PropertyMap.java:382)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:196)
	... 4 more`

**Comment by chhsiao90** [comment] 2018-04-19 06:13
Please wait for the #323 done that the pull request also upgrade the asm version and will support java 10.

**Comment by MrGraversen** [comment] 2018-05-16 05:29
I am also intersted in Java 10 support. I see that the PR is merged, when are you planning on releasing a new version?

**Comment by chhsiao90** [comment] 2018-05-17 08:18
I will release this week.

**Comment by chhsiao90** [comment] 2018-05-21 18:42
modelmapper v2.0 just release, please take a look.

**Closed by chhsiao90** 2018-05-21 18:42 UTC
Labels: Bug
