### ISSUE TITLE
Handle circular reference detection for Strings with same reference

### ISSUE THREAD

**Issue by adamcrevel** [modelmapper/modelmapper#174] opened 2016-04-18 17:07 UTC
For issue #101 it looks like boxed primitives were handled separately due to the caching of certain values (e.g. small integers). I believe this issue also applies to Strings (due to String interning).

The fix may be as simple as adding String to the map(s) in this static block:
https://github.com/jhalterman/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/util/Primitives.java#L37

This is the test mentioned on issue #15 (linked in issue #101) modified for Strings:

public class Test {

```
public static void main(String args[]){
    // Create mapper
    ModelMapper mapper = new ModelMapper();

    // Add custom converter mapping on Integer
    mapper.addConverter(new AbstractConverter<String, ComplexObject>() {
        @Override
        protected ComplexObject convert(String source) {;
            return new ComplexObject(source);
        }
    });

    // Create a source object with two integers wrapping the SAME VALUE
    SourceObject sourceObject = new SourceObject("10", "10");

    // Create a destination (no matter its params)
    DestinationObject destinationObject =  new DestinationObject("30", new ComplexObject("40"));

    // Map the source to the destination
    // => Because of https://www.owasp.org/index.php/Java_gotchas#Immutable_Objects_.2F_Wrapper_Class_Caching
    // complexObject and id are seen like the same value by the circular reference mechanism.
    mapper.map(sourceObject, destinationObject);
}

static class SourceObject {
    private String complexObject;
    private String id;
    public SourceObject(String id, String complexObject) {
        this.id = id;
        this.complexObject = complexObject;
    }
    public String getComplexObject() {
        return complexObject;
    }
    void setComplexObject(String complexObject) {
        this.complexObject = complexObject;
    }
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
}

static class DestinationObject {
    private ComplexObject complexObject;
    private String id;
    public DestinationObject(){/*non-private no-argument constructor for mapping*/};
    public DestinationObject(String id, ComplexObject complexObject) {
        this.id = id;
        this.complexObject = complexObject;
    }
    public ComplexObject getComplexObject() {
        return complexObject;
    }
    public void setComplexObject(ComplexObject complexObject) {
        this.complexObject = complexObject;
    }
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
}

static class ComplexObject {
    private String id;
    public ComplexObject(String id){
        this.id = id;
    }
}
```

}

**Comment by chhsiao90** [comment] 2017-03-23 05:43
Cannot reproduce it with master branch ModelMapper.
I think it might be fixed by #177 .

Feel free to reopened if still have problem, thank you!

**Closed by chhsiao90** 2017-03-23 05:43 UTC
