### ISSUE TITLE
Mapping Source object to Destination object

### ISSUE THREAD

**Issue by goodlifeinc** [modelmapper/modelmapper#386] opened 2018-08-16 11:17 UTC
Hi guys,
First of all thanks for this great library.

A few days ago I have change my dependency on this project from 0.7.5 to 2.1.0 and noticed that the method

    public void map(Object source, Object destination)

changed its behavior, and its not mapping inner lists as it used to.

Here is a simple example:

    // setup
    Inner inner = new Inner();
    inner.setDescription("domain");
    inner.setName("domain");
    Outer outer = new Outer();
    outer.setName("domain");
    outer.setInner(Arrays.asList(inner));

    OuterDTO outerDTO = new OuterDTO();
    outerDTO.setName("dto");
    InnerDTO innerDTO = new InnerDTO();
    innerDTO.setDescription("dto");
    outerDTO.setInner(Arrays.asList(innerDTO));

    // act
    getModelMapper().map(outer, outerDTO);

And this is the getModelMapper() method:

    ModelMapper getModelMapper() {
        ModelMapper mapper = new ModelMapper();
        Condition<?, ?> isNotNullAndEmpty = new AbstractCondition<Object, Object>() {
            @Override
            public boolean applies(MappingContext<Object, Object> context) {
                if (context.getSource() instanceof Collection) {
                    Collection<?> collection = (Collection<?>) context.getSource();
                    return collection != null;
                }
                return true;
            }
        };
        mapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
        mapper.getConfiguration().setPropertyCondition(isNotNullAndEmpty);
        mapper.getConfiguration().setFieldMatchingEnabled(true);

        return mapper;
    }

As a result of the mapping in version 0.7.5 I get the following:

    {
        "name": "domain",
        "inner": [
            {
                "name": "domain",
                "description": "domain"
            }
        ]
    }

And with version 2.1.0 is this:

    {
        "name": "domain",
        "inner": [
            {
                "name": null,
                "description": "dto"
            }
        ]
    }

Could you please tell me is this the expected behavior in version 2.1.0 or am I missing some kind of configuration that need to be done?

N.B. With version 0.7.5 the modelMapper was really intelligent when mapping inner lists and it was not just copying them from source to destination but was comparing them and chaning inner properties when they were different.

**Comment by chhsiao90** [comment] 2018-08-16 11:51
hi @goodlifeinc ,

Thanks for reporting this issue and the detail information. Confirm this is a bug caused by #362 for issue #360. I will have a fix for it.

Before that, I would like to ask that is there any reason that you don't use `modelMapper.map(outer, OutderDTO.class)` to create a new instance of dto. Instead, you use `modelMapper.map(outer, outerDto)` to overwrite the exist one. Thanks.

**Comment by goodlifeinc** [comment] 2018-08-16 12:30
Well I don't have but I think in 0.7.5, as I showed in the second example, it maps them one by one, if in the destination list are more items than in the source list, they get left there without any interactions.

The other case when the source list has more items, they get added to the destination. 

Does this make sense?

**Comment by chhsiao90** [comment] 2018-08-16 12:38
Yes, I will have a fix for this, thanks for the feedback.

**Closed** 2018-08-20 01:28 UTC
Labels: Bug

**Comment by parveenkumardeeva** [comment] 2018-08-22 04:05
Hi,

@chhsiao90 I'm just using ModelMapper via following configs:

```
 ModelMapper mapper = new ModelMapper();
 mapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
```

I have two classes: 

```
public class Cart {
    private List<Items> items;
}

public class UpdateCart {
    private List<Items> items;
}
```

When I'm mapping `UpdateCart` to `Cart` ( during updation of Cart process, **`P.S - UpdateCart items are initialized with a new ArrayList(cart.getItems())`** ) then if `UpdateCart` have less number of `items` than `Cart` it's duplicating the common item by the `size` of Cart `items` and removed the all other ones. i.e the Size of the `Cart items` remains the same but have duplicate entries. Is it some kind of bug or I misconfigured something?

**Comment by chhsiao90** [comment] 2018-08-22 05:47
Hi @parveenkumardeeva ,

Here is current implementation:
*If source has more items (source items' size > destination items' size)*
```
modelMapper.map(Source(items=[a, b, c]), Destination(items=[e, f))
// Destination become Destination(items=[a, b, c])
```

*If they have same size (source items' size = destination items' size)*
```
modelMapper.map(Source(items=[a, b, c]), Destination(items=[e, f, g))
// Destination become Destination(items=[a, b, c])
```

*If source has lessitems (source items' size < destination items' size)*
```
modelMapper.map(Source(items=[a, b]), Destination(items=[e, f, g))
// Destination become Destination(items=[a, b, g])
```

What's your use case that have different size of source and destination items?
For the author opened this issue, he tried to update the entities from the source, so they always have same size.

**Comment by parveenkumardeeva** [comment] 2018-08-22 06:05
Yes, Exactly this is happening as you provided into the example.

But I want to forget what's into the Destination items (Don't use them). Just copy all items from the Source to Destination. Either it's null or Some items.

Is it possible via current implementation?

**Comment by chhsiao90** [comment] 2018-08-22 06:07
you can just ```modelMapper.map(source, Destination.class)``` to always create a new instance.

**Comment by parveenkumardeeva** [comment] 2018-08-22 06:13
The problem is that all my source code is using `modelMapper.map(source, destination)`. Where destination is the object retrieved from the DB. And it have many more fields which should not get update under any circumstances.

I'm only using it during update process. During creation the implementation provided by you is fine.

**Comment by parveenkumardeeva** [comment] 2018-08-22 06:40
Is there any other way through which I can obtain the desired result?

**Comment by chhsiao90** [comment] 2018-08-22 06:41
Okay, then you should try custom property mapping with a property provider that creates a new ArrayList.

**For Java 8**
```java
modelMapper.typeMap(UpdateCart.class, Cart.class)
  .addMappings(mapper -> mapper.with(req -> new ArrayList<Items>()).map(UpdateCart::getItems, Cart::setItems));
```

**For Java 6/7**
```java
modelMapper.addMappings(new PropertyMap<UpdateCart, Cart>() {
  @Override
  protected configure() {
    with(new Provider<Items>() {
      @Override
      public T get(ProvisionRequest<List<Items>> request) {
         return new ArrayList<Items>();
      }
    }).map().setItems(source.getItems());
  }
});
```

**Comment by parveenkumardeeva** [comment] 2018-08-22 06:58
OK Thanks, It's working fine by adding Mappings. I initially thought it should work like that by default. Anyway thanks again.
