### ISSUE TITLE
IllegalArgumentException with java.util.Map after subsequent call of 'map' method

### ISSUE THREAD

**Issue by mrkeuz** [modelmapper/modelmapper#194] opened 2016-12-08 19:19 UTC
IllegalArgumentException throws after subsequent call of 'map' method with different subsets in java.util.Map

Conditions for reproduce:
1. Singleton ModelMapper 
1. Mapping java.util.Map to JavaBean class
1. JavaBean with Getters and Setting 
1. Subsequent call of 'map' method 
1. First subset entries in Map greater than second (i.e two fields then one)

But Exception does not throws on bean without setters and getters.

Example for reproduce 

``` Java
import org.modelmapper.ModelMapper;

import java.util.HashMap;
import java.util.Map;

public class MapperIssue {

    public static void main(String[] args) {
        ModelMapper modelMapper = new ModelMapper();

        //First mapping
        Map<String, String> source = new HashMap<>();
        source.put("age", "20");
        source.put("name", "Bob");
        User dest = new User();
        modelMapper.map(source, dest);

        //Second mapping
        User dest2 = new User();
        Map<String, String> map2 = new HashMap<>();
        map2.put("address", "place");
        modelMapper.map(map2, dest2);

        //throws IllegalArgumentException

        System.out.println(source);
        System.out.println(map2);
    }

    public static class User {
        private String name;
        private String age;
        private String address;

        public String getName() {
            return name;
        }

        public void setName(String fName) {
            this.name = fName;
        }

        public String getAddress() {
            return address;
        }

        public void setAddress(String address) {
            this.address = address;
        }

        public String getAge() {
            return age;
        }

        public void setAge(String age) {
            this.age = age;
        }

    }
}
```

Exception: 

Exception in thread "main" org.modelmapper.MappingException: ModelMapper mapping errors:

1) Error mapping java.util.HashMap to MapperIssue$User

1 error
	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:374)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:69)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:497)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:381)
	at MapperIssue.main(MapperIssue.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalArgumentException
	at org.modelmapper.internal.valueaccess.MapValueReader.get(MapValueReader.java:31)
	at org.modelmapper.internal.valueaccess.MapValueReader.get(MapValueReader.java:28)
	at org.modelmapper.internal.PropertyInfoImpl$ValueReaderPropertyInfo.getValue(PropertyInfoImpl.java:151)
	at org.modelmapper.internal.MappingEngineImpl.resolveSourceValue(MappingEngineImpl.java:189)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:156)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:131)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:92)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:60)
	... 8 more

Process finished with exit code 1

**Comment by mrkeuz** [comment] 2016-12-09 13:45
@jhalterman I have a little question. Is there some simple way to avoid "caching" of mappings rules for ModelMapper instance? 
I.e. for avoid "cache" of mapping rules for mapping from java.util.Map to any class and reuse singleton  instance of modelMapper for map from java.util.Map.

**Comment by chhsiao90** [comment] 2017-03-28 06:24
Thanks for the reporting!

I had a PR for this that I proposed ModelMapper should not cache TypeMap unless the destination is full mapped.
I think it might resolve your problem.



> Is there some simple way to avoid "caching" of mappings rules for ModelMapper instance?

I think you cannot avoid caching.

> I.e. for avoid "cache" of mapping rules for mapping from java.util.Map to any class and reuse singleton instance of modelMapper for map from java.util.Map.

Different destination type would use different TypeMap, I think that's not a big problem.

If there is still some situation not covered, please kindly let me know, thank you 😄

**Comment by gbsmit03** [comment] 2017-06-29 04:05
I see that this is stated as resolved in #210 but this issue is still opened here. I'm running into this issue in v1.0.0.

**Comment by chhsiao90** [comment] 2017-06-30 01:15
@gbsmit03 - I can run the code successfully. Can you provide your use case and the exception stacktrace? Thanks

**Comment by gbsmit03** [comment] 2017-06-30 13:46
_note. I had to update the pom.xml at https://github.com/gbsmit03/modelmappertester/tree/master . I let the my IDE resolve my dependencies and it pick up one of my internal jars._

@chhsiao90 


I have a simple POJO with getters and setters
```java
public class TestPojo {

    private Long id;
    private String name;

    public void setId(Long id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return "TestPojo{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
```

The use case, is when I give ModelMapper a source that is a `Map<>` and the map contains all the fields that the destination object has it works fine. The problem is any usage of the same instance of ModelMapper, using the same destination and source types will fail if the source map does not have entries for all the fields for the destination object. The issue only shows up after I map with a source `Map<>` that contains all the fields for the destination object.

Here is a simple junit  test I used to test it
```java
public class TestFromMapToPojo {

    @Test
    public void testLinkedHashMap1() {
        final ModelMapper modelMapper = new ModelMapper();
        
        //Map a map with all the pojo fields set
        Map<String, Object> mapOfValues = Maps.newLinkedHashMap();
        mapOfValues.put("id", 99L);
        mapOfValues.put("name", "mock name");

        final TestPojo testPojo1 = modelMapper.map(mapOfValues, TestPojo.class);

        System.out.println(testPojo1);

        //Map a map with fields set and a field that does not map to anything on the pojo
        Map<String, Object> mapOfUnmappedFields = Maps.newLinkedHashMap();
        mapOfUnmappedFields.put("id", 99L);

        final TestPojo testPojo2 = modelMapper.map(mapOfUnmappedFields, TestPojo.class);

        System.out.println(testPojo2);
    }

}
```


Here is my unit test results with stack trace
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestFromMapToPojo
TestPojo{id=99, name='mock name'}
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.108 sec <<< FAILURE!
testLinkedHashMap1(TestFromMapToPojo)  Time elapsed: 0.067 sec  <<< ERROR!
org.modelmapper.MappingException: ModelMapper mapping errors:

1) Error mapping java.util.LinkedHashMap to TestPojo

1 error
	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:374)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:69)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:528)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:371)
	at TestFromMapToPojo.testLinkedHashMap1(TestFromMapToPojo.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalArgumentException
	at org.modelmapper.internal.valueaccess.MapValueReader.get(MapValueReader.java:31)
	at org.modelmapper.internal.valueaccess.MapValueReader.get(MapValueReader.java:28)
	at org.modelmapper.internal.PropertyInfoImpl$ValueReaderPropertyInfo.getValue(PropertyInfoImpl.java:154)
	at org.modelmapper.internal.MappingEngineImpl.resolveSourceValue(MappingEngineImpl.java:195)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:160)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:135)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:92)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:60)
	... 32 more


Results :

Tests in error: 
  testLinkedHashMap1(TestFromMapToPojo): ModelMapper mapping errors:(..)


```

**Closed** 2017-07-01 04:35 UTC
Labels: Bug

**Comment by chhsiao90** [comment] 2017-07-01 04:37
@gbsmit03 - Thanks for the report, that's really a bug! Had been fixed by #253

**Comment by gbsmit03** [comment] 2017-07-01 18:45
thanks for the fix @chhsiao90.

**Comment by chhsiao90** [comment] 2017-07-08 07:47
@gbsmit03 - this had been release to v1.1.0, please have a try, thanks!
